services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark_scenario_2
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./:/data
    ports:
      - 3002:3000 # Different port to avoid conflict if both are up
      - 3003:3001
    restart: unless-stopped
