services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark_scenario_3
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./:/data
    ports:
      - 3004:3000
    restart: unless-stopped
